### ISSUE TITLE
scrape_games not returning xC, yC

### ISSUE THREAD

**Issue by mattcane** [HarryShomer/Hockey-Scraper#13]
When I run `scrape_games` the `pbp` dataframe returned has `NaN` for all x and y coordinates for all plays. I _think_ that the issue is in `nhl.pbp.json_pbp.get_pbp` which seems to get an empty dict returned from `shared.scrape_page` even though directly calling `scrape_page` on it's own seems to work.

I'm running python 3.7.3, hockey_scraper version 1.32.4

Sample code:

~~~~
import hockey_scraper as hs
import json

# Returns a pandas df where xC, yC are null
hs.scrape_games([2016020001], data_format = 'Pandas')

# Returns an empty dict and error message: Json pbp for game [2016020001] is either not there or can't be obtained
hs.nhl.pbp.json_pbp.get_pbp([2016020001])

# Returns a play with x and y coordinates which are not null
json.loads(hs.shared.scrape_page('http://statsapi.web.nhl.com/api/v1/game/2016020001/feed/live'))['liveData']['plays']['allPlays'][3]
~~~~

**Comment by HarryShomer** [comment]
Hey Matt,

I won't be able to test this until I get home but it looks like the issue is that the NHL changed the coordinates field in their api from 'xC' and 'yC' to 'x' and 'y'. So nothing major. 

Also the reason why calling 'json_pbp.get_pbp' is throwing an error message is because the function takes a game_id (string or int) and not a list.

**Comment by HarryShomer** [comment]
> I won't be able to test this until I get home but it looks like the issue is that the NHL changed the coordinates field in their api from 'xC' and 'yC' to 'x' and 'y'. So nothing major.

Ok, I just took a look and never mind, I'm full of shit. Took a quick look and assumed that was the issue. Not sure why I assumed they stored them as yC and xC.

Nevertheless, the issue is with 'eventTypeId' field for each play. Just fixed it. 

There is also an (I assume) unrelated issue with the ESPN data as well. So any update will have to wait until that's resolved.

Thanks for pointing the original issue out.

**Comment by HarryShomer** [comment]
@mattcane Should be good now. If you still have a problem you can reopen the issue.

Also again, thanks for letting me know.

**Comment by mattcane** [comment]
Thanks, much appreciated!
