### ISSUE TITLE
scrapping 2014-04-09 generates value error 

### ISSUE THREAD

**Issue by castorgit** [HarryShomer/Hockey-Scraper#17]
Scrapping null values generates errors

hockey_scraper.scrape_date_range('2014-04-09', '2014-04-10', False)
generates value error. This is because somehow data from that day has empty or null values. 
I added a line to html_pbp.py before the astype conversion to eliminate these values.
now it works

    game_df = game_df.replace(r'^\s*$', '0.0', regex=True)
    game_df.Seconds_Elapsed = game_df.Seconds_Elapsed.astype(float)

**Comment by HarryShomer** [comment]
Hey @castorgit,

Thanks for bringing this to my attention. This issue is now fixed in the most recent commit 2c92d89dccc54bb8a36304a555b4e7b0a6dbf9bc (note: In the future please feel free to open up a merge request). I also fixed it on pypi so you can reinstall the package if you like.

In case you are interested, the error occurred when trying to scrape game 2013020971. This was the game that Rich Peverley collapased mid-game and the game had to be resumed at a later date. Because of this they included the goal scored as one of the first lines in the pbp with no time associated with it. And up until now, when no time was present for an event we defaulted to an empty string for the seconds_elapsed column (see function html_pbp.add_time).

Best,
Harry

**Comment by castorgit** [comment]
Ok. Great. Thanks for your response. 
I believe your scrapping package is just the best for NHL games.
I'm using it to analyze goal shots in a Data Science project, and works perfectly.
![kane_18-19](https://user-images.githubusercontent.com/30628981/81779974-04b41d80-94f6-11ea-88c3-4857f013a13a.png)
