### ISSUE TITLE
scraper not working on Python 2.7, Windows 10

### ISSUE THREAD

**Issue by moptis** [HarryShomer/Hockey-Scraper#4]
@HarryShomer  Thanks for putting this together. Any idea why I'm getting the below import error on Python 2.7 and Windows 10?

Thanks!

![image](https://user-images.githubusercontent.com/32751681/44691444-e05f9700-aa1b-11e8-8674-b0ebaddddc1b.png)

**Comment by HarryShomer** [comment]
@moptis Worked fine on my machine (though I have a mac). With that said, I'm pretty sure the issue is with line 202 in shared.py:

![screen shot 2018-08-27 at 7 33 36 pm](https://user-images.githubusercontent.com/25351167/44692328-6f76aa00-aa30-11e8-9981-b58e55018333.png)

I'm guessing you got either a HTTP or Connection error when requesting the Json Schedule page which then led to the function returning the page as None. And then that's causing an issue with Json.loads (it's on line 28 in the third to last block in the stack trace) because it can't None.

This is just a guess though. Can you try running it a few more times and telling me what happens?

**Comment by mcbarlowe** [comment]
I've been looking into this as well and it works on my machine which is a mac as well but if the problem persists i have a windows 10 machine i can load it on to and try it out. I'd also suggest trying different game numbers as well as sometimes the older numbers will throw time out errors in addition.

**Comment by HarryShomer** [comment]
@mcbarlowe Thanks Matt. If it comes to that I'd appreciate it. 

Also, I think you may be right on older games. Another important one is how spread apart the games are. Here it is scraping the schedule from 2007-2009. It's a lot of info so it's liable to timeout.

**Comment by HarryShomer** [comment]
@mcbarlowe Thanks Matt. If it comes to that I'd appreciate it. 

Also, I think you may be right on older games. Another important one is how spread apart the games are. Here it is scraping the schedule from 2007-2009. It's a lot of info so it's liable to timeout.

**Comment by moptis** [comment]
@mcbarlowe Same problem with newer games, but good suggestion.

@HarryShomer That makes sense. I was trying it out on a work computer and it's likely that the HTTP error was due to a firewall. I'll try it out at home at let you know.

**Comment by HarryShomer** [comment]
@moptis Any update on this?

**Comment by HarryShomer** [comment]
Ok, I'm going to consider this issue closed. I'll assume the bug I mentioned above was the problem. You may reopen this if you feel the need.
